import type { User, School, Student, Incident, Agency, PermissionGroup, WorkflowRule, AuditLog } from "./types"

// Demo Schools
export const schools: School[] = [
  {
    id: "school-1",
    name: "Oakridge Academy",
    phone: "020 7123 4567",
    email: "info@oakridge.edu",
    address: "123 Education Lane, London, SW1 2AB",
    logo: "/images/logo-oakridge.png",
    allowedDomains: ["oakridge.edu"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-15"),
  },
  {
    id: "school-2",
    name: "Riverdale High School",
    phone: "020 7987 6543",
    email: "admin@riverdale.edu",
    address: "456 Learning Road, Manchester, M1 3CD",
    logo: "/images/logo-riverdale.png",
    allowedDomains: ["riverdale.edu"],
    createdAt: new Date("2023-02-20"),
    updatedAt: new Date("2023-02-20"),
  },
]

// Demo Users
export const users: User[] = [
  {
    id: "user-1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@oakridge.edu",
    phone: "07700 900123",
    jobTitle: "Designated Safeguarding Lead",
    department: "Safeguarding",
    role: "dsl",
    schoolId: "school-1",
    profileImage: "/images/users/john-smith.jpg",
    lastLogin: new Date("2024-03-24T08:30:00"),
    status: "active",
    createdAt: new Date("2023-01-20"),
    permissionGroups: ["group-1"],
    studentAccess: [],
    categoryAccess: {},
  },
  {
    id: "user-2",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@oakridge.edu",
    phone: "07700 900124",
    jobTitle: "Head Teacher",
    department: "Leadership",
    role: "admin",
    schoolId: "school-1",
    profileImage: "/images/users/sarah-johnson.jpg",
    lastLogin: new Date("2024-03-23T17:15:00"),
    status: "active",
    createdAt: new Date("2023-01-20"),
    permissionGroups: ["group-2"],
    studentAccess: ["student-1", "student-2"],
    categoryAccess: {
      "student-1": ["Bullying", "Attendance"],
      "student-2": ["Bullying", "Attendance", "Mental Health"],
    },
  },
  {
    id: "user-3",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@oakridge.edu",
    phone: "07700 900125",
    jobTitle: "Year 7 Head",
    department: "Pastoral",
    role: "staff",
    schoolId: "school-1",
    profileImage: "/images/users/michael-brown.jpg",
    lastLogin: new Date("2024-03-24T09:45:00"),
    status: "active",
    createdAt: new Date("2023-01-25"),
    permissionGroups: ["group-3"],
    studentAccess: ["student-1", "student-2"],
    categoryAccess: {},
  },
  {
    id: "user-4",
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@riverdale.edu",
    phone: "07700 900126",
    jobTitle: "Designated Safeguarding Lead",
    department: "Safeguarding",
    role: "dsl",
    schoolId: "school-2",
    profileImage: "/images/users/emma-wilson.jpg",
    lastLogin: new Date("2024-03-23T16:20:00"),
    status: "active",
    createdAt: new Date("2023-02-22"),
    permissionGroups: ["group-4"],
    studentAccess: [],
    categoryAccess: {},
  },
  {
    id: "user-5",
    firstName: "David",
    lastName: "Taylor",
    email: "david.taylor@admin.comunitylink.org",
    phone: "07700 900127",
    jobTitle: "System Administrator",
    department: "IT",
    role: "super_user",
    schoolId: "school-1",
    profileImage: "/images/users/david-taylor.jpg",
    lastLogin: new Date("2024-03-24T10:15:00"),
    status: "active",
    createdAt: new Date("2023-01-15"),
    permissionGroups: [],
    studentAccess: [],
    categoryAccess: {},
  },
]

// Demo Students
export const students: Student[] = [
  {
    id: "student-1",
    firstName: "Oliver",
    lastName: "Williams",
    dateOfBirth: new Date("2011-05-12"),
    yearGroup: "Year 7",
    tutor: "7A",
    schoolId: "school-1",
    address: "23 Cherry Lane, London, N1 5TY",
    emergencyContacts: [
      {
        id: "ec-1",
        name: "Linda Williams",
        relationship: "Mother",
        phone: "07700 900234",
        email: "linda.williams@example.com",
        address: "23 Cherry Lane, London, N1 5TY",
      },
      {
        id: "ec-2",
        name: "Robert Williams",
        relationship: "Father",
        phone: "07700 900235",
        email: "robert.williams@example.com",
        address: "23 Cherry Lane, London, N1 5TY",
      },
    ],
    safeguardingStatus: "CIN",
    lastIncidentDate: new Date("2024-03-15"),
    hasConfidentialInformation: true,
    agencies: ["agency-1"],
    siblings: ["student-3"],
    senStatus: "SEND Support",
    ehcpStatus: "assessment_phase",
    ethnicity: "White British",
    nationality: "British",
    religion: "Christian",
    eal: false,
    languages: ["English"],
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "student-2",
    firstName: "Sophia",
    lastName: "Jones",
    dateOfBirth: new Date("2010-11-24"),
    yearGroup: "Year 8",
    tutor: "8B",
    schoolId: "school-1",
    address: "45 Maple Road, London, E2 6RT",
    emergencyContacts: [
      {
        id: "ec-3",
        name: "Patricia Jones",
        relationship: "Mother",
        phone: "07700 900236",
        email: "patricia.jones@example.com",
        address: "45 Maple Road, London, E2 6RT",
        isRisk: true,
        riskNotes: "Court order in place. No contact allowed.",
      },
      {
        id: "ec-4",
        name: "Thomas Jones",
        relationship: "Father",
        phone: "07700 900237",
        email: "thomas.jones@example.com",
        address: "87 Oak Street, London, E2 8UI",
      },
    ],
    safeguardingStatus: "CP",
    lastIncidentDate: new Date("2024-03-20"),
    hasConfidentialInformation: true,
    agencies: ["agency-1", "agency-2"],
    senStatus: "None",
    ehcpStatus: "none",
    ethnicity: "Bangladeshi",
    nationality: "British",
    religion: "Islam",
    eal: true,
    languages: ["Bengali", "English"],
    createdAt: new Date("2023-01-26"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "student-3",
    firstName: "Harry",
    lastName: "Williams",
    dateOfBirth: new Date("2013-02-18"),
    yearGroup: "Year 5",
    tutor: "5C",
    schoolId: "school-1",
    address: "23 Cherry Lane, London, N1 5TY",
    emergencyContacts: [
      {
        id: "ec-5",
        name: "Linda Williams",
        relationship: "Mother",
        phone: "07700 900234",
        email: "linda.williams@example.com",
        address: "23 Cherry Lane, London, N1 5TY",
      },
      {
        id: "ec-6",
        name: "Robert Williams",
        relationship: "Father",
        phone: "07700 900235",
        email: "robert.williams@example.com",
        address: "23 Cherry Lane, London, N1 5TY",
      },
    ],
    safeguardingStatus: "None",
    hasConfidentialInformation: false,
    agencies: [],
    siblings: ["student-1"],
    senStatus: "None",
    ehcpStatus: "none",
    ethnicity: "White British",
    nationality: "British",
    religion: "Christian",
    eal: false,
    languages: ["English"],
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2023-01-25"),
  },
  {
    id: "student-4",
    firstName: "Emily",
    lastName: "Davis",
    dateOfBirth: new Date("2012-07-30"),
    yearGroup: "Year 6",
    tutor: "6A",
    schoolId: "school-2",
    address: "12 Willow Close, Manchester, M3 4PL",
    emergencyContacts: [
      {
        id: "ec-7",
        name: "Karen Davis",
        relationship: "Mother",
        phone: "07700 900238",
        email: "karen.davis@example.com",
        address: "12 Willow Close, Manchester, M3 4PL",
      },
    ],
    safeguardingStatus: "LAC",
    lastIncidentDate: new Date("2024-03-10"),
    hasConfidentialInformation: true,
    agencies: ["agency-3"],
    senStatus: "EHCP",
    ehcpStatus: "final_issued",
    ethnicity: "Black African",
    nationality: "British",
    religion: "Christian",
    eal: false,
    languages: ["English"],
    createdAt: new Date("2023-02-24"),
    updatedAt: new Date("2024-03-10"),
  },
]

// Demo Incidents
export const incidents: Incident[] = [
  {
    id: "incident-1",
    studentId: "student-1",
    reportedBy: "user-3",
    reportDate: new Date("2024-03-15T09:30:00"),
    incidentDate: new Date("2024-03-15T08:45:00"),
    category: "Bullying",
    description:
      "Oliver reported being bullied by older students during break time. They took his lunch and made threatening comments.",
    actionsTaken: "Spoke with Oliver and provided reassurance. Identified the students involved for follow-up.",
    followUpRequired: true,
    followUpNotes: "Need to speak with the identified students and their form tutors.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-03-15T09:30:00"),
    updatedAt: new Date("2024-03-15T09:30:00"),
  },
  {
    id: "incident-2",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-20T14:15:00"),
    incidentDate: new Date("2024-03-20T13:00:00"),
    category: "Disclosure",
    description: "Sophia disclosed concerning information about home situation during a one-to-one session.",
    bodyMap: [
      {
        x: 120,
        y: 80,
        note: "Bruising on right arm",
      },
    ],
    actionsTaken: "Documented disclosure, reassured student that sharing was the right thing to do.",
    followUpRequired: true,
    followUpNotes: "Urgent meeting with social worker scheduled.",
    attachments: [
      {
        id: "attach-1",
        name: "Disclosure Notes.pdf",
        type: "application/pdf",
        url: "/files/disclosure-notes.pdf",
        uploadedBy: "user-1",
        isConfidential: true,
        uploadDate: new Date("2024-03-20T14:30:00"),
      },
    ],
    isConfidential: true,
    status: "escalated",
    loggedByStaffId: "user-1",
    agencyId: "agency-1",
    createdAt: new Date("2024-03-20T14:15:00"),
    updatedAt: new Date("2024-03-20T15:00:00"),
  },
  {
    id: "incident-3",
    studentId: "student-4",
    reportedBy: "user-4",
    reportDate: new Date("2024-03-10T11:20:00"),
    incidentDate: new Date("2024-03-10T10:45:00"),
    category: "Attendance",
    description: "Emily has missed 3 days of school this week with no communication from carers.",
    actionsTaken: "Called foster placement. They reported Emily has been refusing to attend school.",
    followUpRequired: true,
    followUpNotes: "Meeting arranged with foster carers and social worker for tomorrow.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-4",
    agencyId: "agency-3",
    createdAt: new Date("2024-03-10T11:20:00"),
    updatedAt: new Date("2024-03-12T15:45:00"),
  },
  // Additional incidents for student-2 (Sophia Jones)
  {
    id: "incident-4",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2023-09-05T10:15:00"),
    incidentDate: new Date("2023-09-05T09:30:00"),
    category: "Attendance",
    description: "Sophia was absent for the first day of the new school year without prior notification.",
    actionsTaken: "Called father who confirmed Sophia was unwell with a fever.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2023-09-05T10:15:00"),
    updatedAt: new Date("2023-09-06T09:00:00"),
  },
  {
    id: "incident-5",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2023-09-18T13:45:00"),
    incidentDate: new Date("2023-09-18T12:30:00"),
    category: "Peer Conflict",
    description: "Sophia was involved in a verbal altercation with another student during lunch break.",
    actionsTaken: "Mediated discussion between both students. Both apologized to each other.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-1",
    createdAt: new Date("2023-09-18T13:45:00"),
    updatedAt: new Date("2023-09-18T15:00:00"),
  },
  {
    id: "incident-6",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2023-10-03T09:20:00"),
    incidentDate: new Date("2023-10-03T08:45:00"),
    category: "Uniform",
    description: "Sophia arrived at school without proper uniform for the third time this term.",
    actionsTaken: "Discussed with Sophia and provided temporary uniform. Called father to discuss the issue.",
    followUpRequired: true,
    followUpNotes: "Father mentioned financial difficulties. Referred to uniform assistance program.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2023-10-03T09:20:00"),
    updatedAt: new Date("2023-10-05T14:30:00"),
  },
  {
    id: "incident-7",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2023-10-17T14:00:00"),
    incidentDate: new Date("2023-10-17T11:15:00"),
    category: "Academic Concern",
    description: "Sophia's English teacher reported that she has not submitted homework for two consecutive weeks.",
    actionsTaken: "Spoke with Sophia who mentioned difficulties understanding the assignments.",
    followUpRequired: true,
    followUpNotes: "Arranged additional support sessions with the English department.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2023-10-17T14:00:00"),
    updatedAt: new Date("2023-10-24T10:15:00"),
  },
  {
    id: "incident-8",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2023-11-02T11:30:00"),
    incidentDate: new Date("2023-11-02T10:45:00"),
    category: "Mental Health",
    description: "Sophia was found crying in the bathroom by a teaching assistant. She expressed feeling overwhelmed.",
    actionsTaken: "Provided immediate emotional support and brought her to a quiet space to talk.",
    followUpRequired: true,
    followUpNotes: "Referred to school counselor for assessment.",
    isConfidential: true,
    status: "resolved",
    loggedByStaffId: "user-1",
    createdAt: new Date("2023-11-02T11:30:00"),
    updatedAt: new Date("2023-11-09T15:45:00"),
  },
  {
    id: "incident-9",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2023-11-15T13:20:00"),
    incidentDate: new Date("2023-11-15T12:30:00"),
    category: "Disclosure",
    description:
      "During counseling session, Sophia mentioned feeling unsafe at home when her mother visits despite court order.",
    actionsTaken: "Documented disclosure and immediately notified DSL team.",
    followUpRequired: true,
    followUpNotes: "Social worker contacted and home visit arranged.",
    isConfidential: true,
    status: "resolved",
    loggedByStaffId: "user-1",
    agencyId: "agency-1",
    createdAt: new Date("2023-11-15T13:20:00"),
    updatedAt: new Date("2023-11-16T09:30:00"),
  },
  {
    id: "incident-10",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2023-11-28T10:00:00"),
    incidentDate: new Date("2023-11-28T09:15:00"),
    category: "Attendance",
    description: "Sophia arrived 45 minutes late to school without explanation.",
    actionsTaken: "Spoke with Sophia who mentioned missing the bus.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2023-11-28T10:00:00"),
    updatedAt: new Date("2023-11-28T10:15:00"),
  },
  {
    id: "incident-11",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2023-12-05T15:30:00"),
    incidentDate: new Date("2023-12-05T14:20:00"),
    category: "Behavior",
    description:
      "Sophia was disruptive during mathematics class, refusing to participate and distracting other students.",
    actionsTaken: "Removed from class temporarily. Discussed behavior expectations.",
    followUpRequired: true,
    followUpNotes: "Meeting with father scheduled to discuss recent behavioral changes.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2023-12-05T15:30:00"),
    updatedAt: new Date("2023-12-07T16:00:00"),
  },
  {
    id: "incident-12",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2023-12-14T11:45:00"),
    incidentDate: new Date("2023-12-14T11:00:00"),
    category: "Physical Health",
    description: "Sophia complained of severe headache and dizziness during PE lesson.",
    actionsTaken: "Sent to medical room for assessment. Temperature was slightly elevated at 37.8°C.",
    followUpRequired: true,
    followUpNotes: "Father collected Sophia from school. Advised to consult GP if symptoms persist.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-1",
    createdAt: new Date("2023-12-14T11:45:00"),
    updatedAt: new Date("2023-12-14T13:30:00"),
  },
  {
    id: "incident-13",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2024-01-09T09:30:00"),
    incidentDate: new Date("2024-01-09T09:00:00"),
    category: "Attendance",
    description:
      "Sophia returned to school after holiday break but has missed the first week of term without explanation.",
    actionsTaken: "Called father who explained they had extended their holiday due to flight cancellations.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-01-09T09:30:00"),
    updatedAt: new Date("2024-01-09T10:00:00"),
  },
  {
    id: "incident-14",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-01-18T14:15:00"),
    incidentDate: new Date("2024-01-18T13:30:00"),
    category: "Peer Conflict",
    description: "Sophia was involved in a physical altercation with another student in the playground.",
    actionsTaken:
      "Separated students and provided first aid for minor scratches. Both students were spoken to separately.",
    followUpRequired: true,
    followUpNotes: "Restorative justice session scheduled. Parents of both students informed.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-1",
    createdAt: new Date("2024-01-18T14:15:00"),
    updatedAt: new Date("2024-01-19T15:00:00"),
  },
  {
    id: "incident-15",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2024-01-25T10:45:00"),
    incidentDate: new Date("2024-01-25T10:30:00"),
    category: "Property Damage",
    description: "Sophia was observed deliberately damaging a school textbook by tearing pages out.",
    actionsTaken: "Confiscated damaged book and discussed the importance of respecting school property.",
    followUpRequired: true,
    followUpNotes: "Father agreed to pay for replacement. Sophia to write apology letter.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-01-25T10:45:00"),
    updatedAt: new Date("2024-01-26T14:30:00"),
  },
  {
    id: "incident-16",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-02-02T13:00:00"),
    incidentDate: new Date("2024-02-02T12:15:00"),
    category: "Mental Health",
    description: "Sophia expressed suicidal thoughts to the school counselor during a scheduled session.",
    actionsTaken: "Immediate risk assessment conducted. Contacted father and CAMHS for urgent assessment.",
    followUpRequired: true,
    followUpNotes: "CAMHS assessment scheduled. Safety plan put in place with father's cooperation.",
    isConfidential: true,
    status: "in_progress",
    loggedByStaffId: "user-1",
    agencyId: "agency-2",
    createdAt: new Date("2024-02-02T13:00:00"),
    updatedAt: new Date("2024-02-02T16:30:00"),
  },
  {
    id: "incident-17",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2024-02-09T09:15:00"),
    incidentDate: new Date("2024-02-09T08:45:00"),
    category: "Attendance",
    description: "Sophia arrived at school but left premises without permission before registration.",
    actionsTaken: "Immediate search of local area. Father contacted. Sophia returned to school after 30 minutes.",
    followUpRequired: true,
    followUpNotes: "Meeting with Sophia and father to discuss serious nature of unauthorized absence.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-02-09T09:15:00"),
    updatedAt: new Date("2024-02-09T11:30:00"),
  },
  {
    id: "incident-18",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-02-15T14:30:00"),
    incidentDate: new Date("2024-02-15T13:45:00"),
    category: "Disclosure",
    description: "Sophia mentioned that her mother had visited the house last weekend despite court order.",
    actionsTaken: "Documented disclosure and contacted social worker immediately.",
    followUpRequired: true,
    followUpNotes: "Social worker to conduct home visit. Police informed of potential breach of court order.",
    isConfidential: true,
    status: "in_progress",
    loggedByStaffId: "user-1",
    agencyId: "agency-1",
    createdAt: new Date("2024-02-15T14:30:00"),
    updatedAt: new Date("2024-02-15T16:00:00"),
  },
  {
    id: "incident-19",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2024-02-22T11:00:00"),
    incidentDate: new Date("2024-02-22T10:30:00"),
    category: "Academic Achievement",
    description:
      "Sophia received excellent results in her mid-term mathematics assessment, showing significant improvement.",
    actionsTaken: "Positive reinforcement provided. Mathematics teacher commended her effort.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-02-22T11:00:00"),
    updatedAt: new Date("2024-02-22T11:15:00"),
  },
  {
    id: "incident-20",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2024-02-29T09:45:00"),
    incidentDate: new Date("2024-02-29T09:30:00"),
    category: "Uniform",
    description: "Sophia arrived at school with inappropriate footwear (trainers instead of black shoes).",
    actionsTaken: "Provided temporary appropriate footwear from lost property.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-02-29T09:45:00"),
    updatedAt: new Date("2024-02-29T10:00:00"),
  },
  {
    id: "incident-21",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-05T13:30:00"),
    incidentDate: new Date("2024-03-05T12:45:00"),
    category: "Peer Conflict",
    description: "Sophia reported being cyberbullied by classmates on social media platforms.",
    actionsTaken: "Gathered evidence of messages. Spoke with students involved and their parents.",
    followUpRequired: true,
    followUpNotes: "Anti-bullying intervention planned. Social media safety workshop to be arranged for the class.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-1",
    createdAt: new Date("2024-03-05T13:30:00"),
    updatedAt: new Date("2024-03-06T15:00:00"),
  },
  {
    id: "incident-22",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2024-03-08T10:15:00"),
    incidentDate: new Date("2024-03-08T09:45:00"),
    category: "Behavior",
    description: "Sophia used inappropriate language towards a teacher during science lesson.",
    actionsTaken: "Removed from class. Reflection session conducted with head of year.",
    followUpRequired: true,
    followUpNotes: "Father informed. Sophia to write letter of apology to teacher.",
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-03-08T10:15:00"),
    updatedAt: new Date("2024-03-09T11:30:00"),
  },
  {
    id: "incident-23",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-12T14:00:00"),
    incidentDate: new Date("2024-03-12T13:30:00"),
    category: "Physical Health",
    description: "Sophia complained of stomach pain and nausea during afternoon lessons.",
    actionsTaken: "Sent to medical room for assessment. Father contacted to collect her from school.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-1",
    createdAt: new Date("2024-03-12T14:00:00"),
    updatedAt: new Date("2024-03-12T15:15:00"),
  },
  {
    id: "incident-24",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2024-03-15T09:30:00"),
    incidentDate: new Date("2024-03-15T09:00:00"),
    category: "Attendance",
    description: "Sophia arrived 30 minutes late to school for the third time this week.",
    actionsTaken: "Discussed punctuality with Sophia. Father contacted to address ongoing issue.",
    followUpRequired: true,
    followUpNotes: "Attendance improvement plan to be put in place with daily monitoring.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-03-15T09:30:00"),
    updatedAt: new Date("2024-03-15T10:00:00"),
  },
  {
    id: "incident-25",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-18T11:45:00"),
    incidentDate: new Date("2024-03-18T11:15:00"),
    category: "Mental Health",
    description:
      "Sophia appeared withdrawn and refused to participate in group activities. When approached, she became tearful.",
    actionsTaken: "Provided quiet space to talk. Sophia mentioned feeling anxious about upcoming assessments.",
    followUpRequired: true,
    followUpNotes: "Referral to school counselor for anxiety management strategies.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-1",
    createdAt: new Date("2024-03-18T11:45:00"),
    updatedAt: new Date("2024-03-18T13:00:00"),
  },
  {
    id: "incident-26",
    studentId: "student-2",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-20T14:15:00"),
    incidentDate: new Date("2024-03-20T13:00:00"),
    category: "Disclosure",
    description: "Sophia disclosed concerning information about home situation during a one-to-one session.",
    bodyMap: [
      {
        x: 120,
        y: 80,
        note: "Bruising on right arm",
      },
    ],
    actionsTaken: "Documented disclosure, reassured student that sharing was the right thing to do.",
    followUpRequired: true,
    followUpNotes: "Urgent meeting with social worker scheduled.",
    attachments: [
      {
        id: "attach-1",
        name: "Disclosure Notes.pdf",
        type: "application/pdf",
        url: "/files/disclosure-notes.pdf",
        uploadedBy: "user-1",
        isConfidential: true,
        uploadDate: new Date("2024-03-20T14:30:00"),
      },
    ],
    isConfidential: true,
    status: "escalated",
    loggedByStaffId: "user-1",
    agencyId: "agency-1",
    createdAt: new Date("2024-03-20T14:15:00"),
    updatedAt: new Date("2024-03-20T15:00:00"),
  },
  {
    id: "incident-27",
    studentId: "student-2",
    reportedBy: "user-2",
    reportDate: new Date("2024-03-22T10:00:00"),
    incidentDate: new Date("2024-03-22T09:30:00"),
    category: "Academic Concern",
    description: "Sophia's science teacher reported that she has not completed any homework assignments this month.",
    actionsTaken: "Discussed with Sophia who mentioned difficulties concentrating at home.",
    followUpRequired: true,
    followUpNotes: "Arranged homework club attendance three times per week.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-03-22T10:00:00"),
    updatedAt: new Date("2024-03-22T11:15:00"),
  },
  {
    id: "incident-28",
    studentId: "student-2",
    reportedBy: "user-3",
    reportDate: new Date("2024-03-25T13:45:00"),
    incidentDate: new Date("2024-03-25T13:15:00"),
    category: "Peer Conflict",
    description: "Sophia was involved in a verbal argument with several students during lunch break.",
    actionsTaken:
      "Mediated discussion between all parties. Root cause appeared to be misunderstanding over social media posts.",
    followUpRequired: true,
    followUpNotes: "Monitoring situation. Digital citizenship workshop planned for class.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-03-25T13:45:00"),
    updatedAt: new Date("2024-03-25T14:30:00"),
  },
  // Feature-rich incident example
  {
    id: "incident-rich-1",
    studentId: "student-1",
    reportedBy: "user-1",
    reportDate: new Date("2024-03-22T10:15:00"),
    incidentDate: new Date("2024-03-22T09:30:00"),
    category: "Physical Abuse",
    description:
      "Oliver was observed with bruising on his right arm and reported that he was grabbed forcefully at home. He appeared distressed when discussing the incident.",
    bodyMap: [
      {
        x: 120,
        y: 80,
        note: "Bruising on right upper arm, approximately 5cm in diameter",
      },
      {
        x: 130,
        y: 90,
        note: "Smaller bruise, finger-shaped marks",
      },
    ],
    actionsTaken:
      "Documented injuries with photographs. Conducted initial safeguarding assessment. Contacted social worker.",
    followUpRequired: true,
    followUpNotes: "Urgent strategy meeting scheduled with social services for tomorrow. Home visit to be arranged.",
    attachments: [
      {
        id: "attach-rich-1",
        name: "Bruise Documentation.pdf",
        type: "application/pdf",
        url: "/files/bruise-documentation.pdf",
        uploadedBy: "user-1",
        isConfidential: true,
        uploadDate: new Date("2024-03-22T10:30:00"),
      },
      {
        id: "attach-rich-2",
        name: "Incident Photos.zip",
        type: "application/zip",
        url: "/files/incident-photos.zip",
        uploadedBy: "user-1",
        isConfidential: true,
        uploadDate: new Date("2024-03-22T10:35:00"),
      },
    ],
    isConfidential: true,
    status: "escalated",
    loggedByStaffId: "user-1",
    agencyId: "agency-1",
    createdAt: new Date("2024-03-22T10:15:00"),
    updatedAt: new Date("2024-03-22T11:00:00"),
  },
  {
    id: "incident-rich-2",
    studentId: "student-1",
    reportedBy: "user-3",
    reportDate: new Date("2024-03-18T14:30:00"),
    incidentDate: new Date("2024-03-18T13:45:00"),
    category: "Attendance",
    description:
      "Oliver has been late to school three times this week. When questioned, he mentioned having trouble sleeping and feeling tired in the mornings.",
    actionsTaken: "Spoke with Oliver about the importance of regular attendance. Will monitor the situation.",
    followUpRequired: true,
    followUpNotes: "Schedule meeting with parents to discuss attendance concerns.",
    isConfidential: false,
    status: "in_progress",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-03-18T14:30:00"),
    updatedAt: new Date("2024-03-18T14:45:00"),
  },
  {
    id: "incident-rich-3",
    studentId: "student-1",
    reportedBy: "user-2",
    reportDate: new Date("2024-03-10T11:20:00"),
    incidentDate: new Date("2024-03-10T10:30:00"),
    category: "Bullying",
    description:
      "Oliver reported being bullied by two Year 8 students during lunch break. They allegedly took his food and made threatening comments.",
    actionsTaken: "Interviewed all students involved. Year 8 students given detention and parents notified.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-03-10T11:20:00"),
    updatedAt: new Date("2024-03-12T09:15:00"),
  },
  {
    id: "incident-rich-4",
    studentId: "student-1",
    reportedBy: "user-1",
    reportDate: new Date("2024-02-28T15:10:00"),
    incidentDate: new Date("2024-02-28T14:20:00"),
    category: "Mental Health",
    description:
      "Oliver appeared withdrawn during class and was found crying in the bathroom. He mentioned feeling overwhelmed with schoolwork and home pressures.",
    actionsTaken: "Provided immediate emotional support. Referred to school counselor for assessment.",
    followUpRequired: true,
    followUpNotes: "Schedule weekly check-ins with school counselor. Monitor mood and behavior in class.",
    attachments: [
      {
        id: "attach-rich-3",
        name: "Counselor Referral.pdf",
        type: "application/pdf",
        url: "/files/counselor-referral.pdf",
        uploadedBy: "user-1",
        isConfidential: true,
        uploadDate: new Date("2024-02-28T15:30:00"),
      },
    ],
    isConfidential: true,
    status: "in_progress",
    loggedByStaffId: "user-1",
    createdAt: new Date("2024-02-28T15:10:00"),
    updatedAt: new Date("2024-02-28T16:00:00"),
  },
  {
    id: "incident-s1-1",
    studentId: "student-1",
    reportedBy: "user-3",
    reportDate: new Date("2024-01-15T09:30:00"),
    incidentDate: new Date("2024-01-15T08:45:00"),
    category: "Attendance",
    description: "Oliver was absent without explanation.",
    actionsTaken: "Called parents who confirmed he was unwell with flu symptoms.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-3",
    createdAt: new Date("2024-01-15T09:30:00"),
    updatedAt: new Date("2024-01-15T10:00:00"),
  },
  {
    id: "incident-s1-2",
    studentId: "student-1",
    reportedBy: "user-2",
    reportDate: new Date("2024-01-22T13:15:00"),
    incidentDate: new Date("2024-01-22T12:30:00"),
    category: "Behavior",
    description: "Oliver was disruptive during mathematics class, refusing to participate.",
    actionsTaken: "Spoke with Oliver about classroom expectations. He apologized for his behavior.",
    followUpRequired: false,
    isConfidential: false,
    status: "resolved",
    loggedByStaffId: "user-2",
    createdAt: new Date("2024-01-22T13:15:00"),
    updatedAt: new Date("2024-01-22T14:00:00"),
  },
  {
    id: "incident-s1-3",
    studentId: "student-1",
    reportedBy: "user-1",
    reportDate: new Date("2023-12-05T10:45:00"),
    incidentDate: new Date("2023-12-05T10:15:00"),
    category: "Neglect",
    description: "Oliver arrived at school without appropriate winter clothing despite freezing temperatures.",
    actionsTaken:
      "Provided Oliver with spare coat from lost property. Contacted parents to discuss appropriate clothing.",
    followUpRequired: true,
    followUpNotes: "Monitor situation as weather gets colder. Consider referral if pattern continues.",
    isConfidential: true,
    status: "in_progress",
    loggedByStaffId: "user-1",
    createdAt: new Date("2023-12-05T10:45:00"),
    updatedAt: new Date("2023-12-05T11:30:00"),
  },
]

// Demo Agencies
export const agencies: Agency[] = [
  {
    id: "agency-1",
    name: "Local Children's Services",
    address: "1 Council Square, London, SW1 1AA",
    phone: "020 7123 1234",
    email: "childrens.services@localauthority.gov.uk",
    details: "Local authority children's social care department.",
    contacts: [
      {
        id: "ac-1",
        name: "James Wilson",
        phone: "020 7123 1235",
        email: "james.wilson@localauthority.gov.uk",
        role: "Social Worker",
      },
      {
        id: "ac-2",
        name: "Amelia Clark",
        phone: "020 7123 1236",
        email: "amelia.clark@localauthority.gov.uk",
        role: "Team Manager",
      },
    ],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-15"),
  },
  {
    id: "agency-2",
    name: "Child and Adolescent Mental Health Services",
    address: "45 Healthcare Avenue, London, E1 7BD",
    phone: "020 7123 5678",
    email: "referrals@camhs.nhs.uk",
    details: "NHS service providing mental health support for children and young people.",
    contacts: [
      {
        id: "ac-3",
        name: "Dr. Rebecca Moore",
        phone: "020 7123 5679",
        email: "rebecca.moore@nhs.net",
        role: "Clinical Psychologist",
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "agency-3",
    name: "Manchester Children's Services",
    address: "22 Town Hall Extension, Manchester, M2 5DB",
    phone: "0161 234 5678",
    email: "childrens.services@manchester.gov.uk",
    details: "Manchester City Council children's social care department.",
    contacts: [
      {
        id: "ac-4",
        name: "Daniel Roberts",
        phone: "0161 234 5679",
        email: "daniel.roberts@manchester.gov.uk",
        role: "Social Worker",
      },
    ],
    createdAt: new Date("2023-02-22"),
    updatedAt: new Date("2023-02-22"),
  },
]

// Demo Permission Groups
export const permissionGroups: PermissionGroup[] = [
  {
    id: "group-1",
    name: "DSL Full Access",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "incidents", action: "update" },
      { resource: "incidents", action: "delete" },
      { resource: "students", action: "create" },
      { resource: "students", action: "read" },
      { resource: "students", action: "update" },
      { resource: "students", action: "delete" },
      { resource: "confidential", action: "read" },
      { resource: "confidential", action: "update" },
      { resource: "agencies", action: "create" },
      { resource: "agencies", action: "read" },
      { resource: "agencies", action: "update" },
      { resource: "reports", action: "create" },
      { resource: "reports", action: "read" },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "group-2",
    name: "Leadership Team",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "incidents", action: "update" },
      { resource: "students", action: "read" },
      { resource: "students", action: "update" },
      { resource: "confidential", action: "read" },
      { resource: "agencies", action: "read" },
      { resource: "reports", action: "read" },
      { resource: "users", action: "create" },
      { resource: "users", action: "read" },
      { resource: "users", action: "update" },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "group-3",
    name: "Year Heads",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "incidents", action: "update" },
      { resource: "students", action: "read" },
      { resource: "agencies", action: "read" },
      { resource: "reports", action: "read" },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2023-01-25"),
  },
  {
    id: "group-4",
    name: "DSL Full Access - Riverdale",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "incidents", action: "update" },
      { resource: "incidents", action: "delete" },
      { resource: "students", action: "create" },
      { resource: "students", action: "read" },
      { resource: "students", action: "update" },
      { resource: "students", action: "delete" },
      { resource: "confidential", action: "read" },
      { resource: "confidential", action: "update" },
      { resource: "agencies", action: "create" },
      { resource: "agencies", action: "read" },
      { resource: "agencies", action: "update" },
      { resource: "reports", action: "create" },
      { resource: "reports", action: "read" },
    ],
    schoolId: "school-2",
    createdAt: new Date("2023-02-22"),
    updatedAt: new Date("2023-02-22"),
  },
  {
    id: "group-5",
    name: "Staff",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "students", action: "read" },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2023-01-25"),
  },
  {
    id: "group-6",
    name: "SLT",
    permissions: [
      { resource: "incidents", action: "create" },
      { resource: "incidents", action: "read" },
      { resource: "incidents", action: "update" },
      { resource: "students", action: "read" },
      { resource: "students", action: "update" },
      { resource: "reports", action: "read" },
      { resource: "users", action: "read" },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2023-01-25"),
  },
]

// Demo Workflow Rules
export const workflowRules: WorkflowRule[] = [
  {
    id: "workflow-1",
    name: "Bullying Incident Workflow",
    condition: {
      categories: ["Bullying"],
    },
    steps: [
      {
        id: "step-1",
        type: "notify",
        config: {
          roles: ["dsl"],
          message: "New bullying incident reported",
        },
        nextStepId: "step-2",
      },
      {
        id: "step-2",
        type: "notify",
        config: {
          users: ["user-3"],
          message: "Please review and follow up on this bullying incident",
        },
      },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-02-10"),
  },
  {
    id: "workflow-2",
    name: "Safeguarding Disclosure Workflow",
    condition: {
      categories: ["Disclosure"],
    },
    steps: [
      {
        id: "step-3",
        type: "notify",
        config: {
          roles: ["dsl"],
          urgent: true,
          message: "URGENT: New safeguarding disclosure",
        },
        nextStepId: "step-4",
      },
      {
        id: "step-4",
        type: "condition",
        config: {
          condition: "has_body_map",
          trueStepId: "step-5",
          falseStepId: "step-6",
        },
      },
      {
        id: "step-5",
        type: "notify",
        config: {
          roles: ["dsl", "admin"],
          urgent: true,
          message: "Physical mark noted in disclosure - immediate action required",
        },
      },
      {
        id: "step-6",
        type: "notify",
        config: {
          roles: ["dsl"],
          message: "Please review and assess this disclosure",
        },
      },
    ],
    schoolId: "school-1",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2023-02-15"),
  },
]

// Demo Audit Logs
export const auditLogs: AuditLog[] = [
  {
    id: "audit-1",
    userId: "user-1",
    action: "login",
    details: "User logged in",
    resourceType: "auth",
    resourceId: "user-1",
    timestamp: new Date("2024-03-24T08:30:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-2",
    userId: "user-1",
    action: "view",
    details: "Viewed student profile",
    resourceType: "student",
    resourceId: "student-1",
    timestamp: new Date("2024-03-24T08:35:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-3",
    userId: "user-1",
    action: "view",
    details: "Viewed incident details",
    resourceType: "incident",
    resourceId: "incident-1",
    timestamp: new Date("2024-03-24T08:40:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-4",
    userId: "user-1",
    action: "update",
    details: "Updated incident status to in_progress",
    resourceType: "incident",
    resourceId: "incident-1",
    timestamp: new Date("2024-03-24T08:45:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-5",
    userId: "user-1",
    action: "create",
    details: "Created new incident report",
    resourceType: "incident",
    resourceId: "incident-2",
    timestamp: new Date("2024-03-24T09:15:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-6",
    userId: "user-1",
    action: "upload",
    details: "Uploaded document to incident",
    resourceType: "attachment",
    resourceId: "attach-1",
    timestamp: new Date("2024-03-24T09:20:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-7",
    userId: "user-1",
    action: "logout",
    details: "User logged out",
    resourceType: "auth",
    resourceId: "user-1",
    timestamp: new Date("2024-03-24T12:30:00"),
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "audit-8",
    userId: "user-2",
    action: "login",
    details: "User logged in",
    resourceType: "auth",
    resourceId: "user-2",
    timestamp: new Date("2024-03-24T13:00:00"),
    ipAddress: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "audit-9",
    userId: "user-2",
    action: "view",
    details: "Viewed student profile",
    resourceType: "student",
    resourceId: "student-2",
    timestamp: new Date("2024-03-24T13:05:00"),
    ipAddress: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "audit-10",
    userId: "user-2",
    action: "update",
    details: "Updated student information",
    resourceType: "student",
    resourceId: "student-2",
    timestamp: new Date("2024-03-24T13:10:00"),
    ipAddress: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
]

